server:
  port: 8887
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'shopping-content-ms'
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
mybatis:
  type-aliases-package: com.gec.shopping.pojo
pagehelper:
  helper-dialect: mysql
  reasonable: true
# MinIO对象存储相关配置
minio:
  endpoint:  http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
file:
  staticAccessPath: '/upload/**'
  uploadFolder: 'D:\\file'
 