server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  data:
    solr:
      host: http://127.0.0.1:8080/solr
  application:
    name: 'shopping-search-ms'
