eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8989
spring:
  application:
    name: shopping-zuul
zuul:
  routes:
    api-manager-ms:
      path: /shopping-manager/**
      service-id: shopping-manager-ms
    api-content:
      path: /shopping-content/**
      service-id: shopping-content-ms
    api-search:
      path: /shopping-search/**
      service-id: shopping-search-ms
    api-shop:
      path: /shopping-shop/**
      service-id: shopping-shop-ms

    